/**
 * 常量类
 */

export default class CommonConstants {
  // 待办标题
  static readonly TODO_TITLE: string = '待办';
  // 待办页面的路由
  static readonly TODO_ROUTER: string = "pages/ToDoList";

  static readonly BASE_URL = "http://192.168.0.110:3000";


  // 页面路由
  /**
   * Main page url.
   */
  static readonly MAIN_PAGE_URL: string = 'pages/MainPage';

  /**
   * Login page url.
   */
  static readonly LOGIN_PAGE_URL: string = 'pages/Login';
}